### ISSUE TITLE
destroy method raise exception

### ISSUE THREAD

**Issue by shift-reality** [waynegm/imgViewer2#5]
There is another problem found when calling "imgViewer2('destroy')":

jquery-3.2.1.min.js:2 Uncaught TypeError: this.map.remove is not a function
    at t.(anonymous function).(anonymous function).destroy (imgViewer2.min.js:1:4093)
    at t.(anonymous function).(anonymous function).destroy (jquery-ui.min.js:6:4499)
    at HTMLImageElement.<anonymous> (jquery-ui.min.js:6:5474)
    at Function.each (jquery-3.2.1.min.js:2:2715)
    at r.fn.init.each (jquery-3.2.1.min.js:2:1003)
    at r.fn.init.t.fn.(anonymous function) [as imgViewer2] (jquery-ui.min.js:6:5357)
    at HTMLDocument.<anonymous> (:44)
    at j (jquery-3.2.1.min.js:2:29999)
    at k (jquery-3.2.1.min.js:2:30313)

**Comment by waynegm** [comment]
I can't reproduce this problem. The file I tested with is [here](https://github.com/waynegm/imgViewer2/files/1155537/test.zip).

**this.map.remove** is actually a Leaflet method and I don't understand why jQuery is even being called. If the problem persists can you send me a small example that demonstrates the problem.
